### ISSUE TITLE
Cannot delete Enrollment Flow Wedge

### ISSUE THREAD

**Issue by terrencegf** [cilogon/EmailVerificationEnroller#12]
Attempting to delete a configured EmailVerificationEnroller wedge results in an error:

```
An Internal Error Has Occurred.
Error: An Internal Error Has Occurred.
```

Log message:
```
2024-02-20 17:00:55 Error: [PDOException] SQLSTATE[42S02]: Base table or view not found: 1146 Table 'access_registry_dev.cm_co_petition_email_addresses' doesn't exist
Request URL: /registry/co_enrollment_flow_wedges/delete/8
Stack Trace:
#0 /srv/comanage-registry/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /srv/comanage-registry/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute()
#2 /srv/comanage-registry/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute()
#3 /srv/comanage-registry/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll()
#4 /srv/comanage-registry/lib/Cake/Model/Model.php(3053): DboSource->read()
#5 /srv/comanage-registry/lib/Cake/Model/Model.php(3025): Model->_readDataSource()
#6 /srv/comanage-registry/lib/Cake/Model/Model.php(2855): Model->find()
#7 /srv/comanage-registry/app/Model/Behavior/ChangelogBehavior.php(150): Model->deleteAll()
#8 /srv/comanage-registry/lib/Cake/Utility/ObjectCollection.php(129): ChangelogBehavior->beforeDelete()
#9 /srv/comanage-registry/lib/Cake/Event/CakeEventManager.php(244): ObjectCollection->trigger()
#10 /srv/comanage-registry/lib/Cake/Model/Model.php(2694): CakeEventManager->dispatch()
#11 /srv/comanage-registry/app/Model/AppModel.php(831): Model->delete()
#12 /srv/comanage-registry/lib/Cake/Model/Model.php(2871): AppModel->delete()
#13 /srv/comanage-registry/app/Model/Behavior/ChangelogBehavior.php(150): Model->deleteAll()
#14 /srv/comanage-registry/lib/Cake/Utility/ObjectCollection.php(129): ChangelogBehavior->beforeDelete()
#15 /srv/comanage-registry/lib/Cake/Event/CakeEventManager.php(244): ObjectCollection->trigger()
#16 /srv/comanage-registry/lib/Cake/Model/Model.php(2694): CakeEventManager->dispatch()
#17 /srv/comanage-registry/app/Model/AppModel.php(831): Model->delete()
#18 /srv/comanage-registry/app/Controller/StandardController.php(444): AppModel->delete()
#19 [internal function]: StandardController->delete()
#20 /srv/comanage-registry/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#21 /srv/comanage-registry/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#22 /srv/comanage-registry/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#23 /srv/comanage-registry/app/webroot/index.php(96): Dispatcher->dispatch()
#24 {main}
```

I confirmed that the database does not have any table named "cm_co_petition_email_addresses".

```
MySQL [access_registry_dev]> show tables like '%cm_co_petition%';;
+--------------------------------------------------+
| Tables_in_access_registry_dev (%cm_co_petition%) |
+--------------------------------------------------+
| cm_co_petition_attributes                        |
| cm_co_petition_history_records                   |
| cm_co_petitions                                  |
+--------------------------------------------------+
3 rows in set (0.055 sec)
```

I don't know how to fix this easily. The string `cm_co_petition_email_addresses` does not exist in the code base.

**Comment by ioigoume** [comment]
@terrencegf fix pushed to main

**Comment by terrencegf** [comment]
Confirmed [commit f5a6f35](https://github.com/cilogon/EmailVerificationEnroller/commit/f5a6f3598219cda6f4fd6e4487b2a9b1ec06f7d0) fixes the issue.
